# ~/.config/starship.toml
format = '''
[=======================>](bold purple)
[‚îå‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ>](bold green)
[‚îÇ](bold green)$os$python$directory$git_branch$git_status$rust$package$cmd_duration
[‚îî‚îÄ‚îÄ‚îÄ‚îÄ‚îÄ>](bold green)
[==========>](bold purple)'''

# Command Duration Module Configuration
[cmd_duration]
min_time = 2000  # Show duration if the command takes longer than 2 seconds
show_milliseconds = false  # Only show seconds
format = "took [$duration]($style) "  # Format for displaying the duration
style = "bold yellow"  # Style for the duration text

# OS module configuration for displaying the Debian logo
[os]
format = "[$symbol](bold purple) "  # Display the OS symbol in bold white
disabled = false

[os.symbols]
# Define symbols for various operating systems
Windows = "ÔÖ∫ "  # Windows symbol
Arch = "ÔåÉ "     # Arch Linux symbol
Ubuntu = "Ôåõ "   # Ubuntu symbol
Macos = "ÔÖπ "    # macOS symbol
Debian = "ÔåÜ "   # Debian symbol

# Git Branch Module Configuration
[git_branch]
symbol = "ÓÇ† "  # This is the branch icon symbol
format = "on [$symbol$branch]($style) "  # Format for displaying the branch
style = "bold blue"  # Style for the branch text

# Git Status Module Configuration
[git_status]
format = "[$all_status$ahead_behind]($style)"  # Show all status icons
style = "bold purple"  # Style for the status text

# venv Status Module Configuration
[python]
symbol = "üêç "
format = "[$symbol$virtualenv $version]($style) "
style = "bold green"
detect_extensions = ["py"]
detect_files = []
detect_folders = []