---
services:
  gitlab:
    image: gitlab/gitlab-ce:17.5.5-ce.0
    container_name: gitlab
    ports:
      - 3200:22
      - 8929:8929
      - 4435:443
    volumes:
      - /compose/gitlab/config:/etc/gitlab
      - /compose/gitlab/logs:/var/log/gitlab
      - /compose/gitlab/data:/var/opt/gitlab
    shm_size: "256m"
    deploy:
      resources:
        limits:
          memory: 6g
          cpus: "4"
    healthcheck:
      test:
        - CMD-SHELL
        - curl --fail http://localhost:8929 || exit 0
      interval: 40s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
