---
services:
  portainer:
    image: portainer/portainer-ce:2.33.6
    container_name: portainer
   # ports:
   #     - 8000:8000
   #     - 9443:9443
   #     - 9000:9000 HTTP access
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/docker/volumes/portainer:/data
    healthcheck:
      test: ["CMD", "/portainer", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.local.jacinto.cc`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  proxy:
    external: true
